### ISSUE TITLE
Add hotfix deploy command

### ISSUE THREAD

**Issue by ataylorme** [terminus-plugin-project/terminus-hotfix-plugin#1]
The command should allow deployment of a multidev environment straight to test or live.

The newly created tag should then be [rebased](https://git-scm.com/docs/git-rebase) on top of `master` so subsequent deployments do not overwrite the hotfix.

I am still thinking about how to handle uncommitted code in dev and merge conflicts when applying the hotfix back to `master`. Thoughts/recommendations welcome.

**Comment by sean-e-dietrich** [comment]
@ataylorme is there a way to grab the diff of uncommitted code first and then apply hotfix, then apply uncommitted code diff?

**Comment by ataylorme** [comment]
I am thinking more of uncommitted code when a site is in SFTP mode. My thought is to ask the user if they want to commit the code or abort.

**Comment by sean-e-dietrich** [comment]
That would be my next suggestion if you told me that it wasn't possible to get a diff of code that was uncommitted.

**Comment by ataylorme** [comment]
We could use [`diffstat` on the environment](https://github.com/pantheon-systems/terminus/blob/master/src/Models/Environment.php#L347), it is what powers the `env:diffstat` command. That seems like a lot of work to restore uncommitted SFTP changes when those changes aren't guaranteed to persist anyway.

I think alerting the user there is uncommitted code and asking if they would like to commit it before proceeding or aborting seems reasonable but I am open to hearing more about use cases where uncommitted SFTP changes are a regular occurance and this would cause pain.

**Comment by ataylorme** [comment]
Similarly for merge conflicts applying the hotfix back to `master` I am leaning towards asking the user to abort with a warning about the implication of deleting the hotfix on the next deploy if a merge is not done. The abort can be a prompt, defaulting to yes, with the option to override the abort and continue anyway.

**Comment by uberhacker** [comment]
@ataylorme: Thank you for adding another plugin!  I guess I'm not quite following what you are trying to do here.  Are all these steps something that can be done in git?

**Comment by ataylorme** [comment]
@uberhacker yes, these are steps that users need to do manually now with git. See the [hotfix doc](https://pantheon.io/docs/hotfixes/) for details. Basically, a hotfix is deploying a change straight to test or live without going through the entire workflow.

The main difference between a hotfix and a standard multidev is that a standard multidev is branched from `master` and may contain in-progress code that has not been deployed to live. The `terminus hotfix:env:create` command creates a multidev based off of the latest git reference (the latest deployed tag for test and live) rather than `master`.

The use case I am aiming for here is critical security releases so that they can be deployed as quickly and easily as possible.

Ultimately I want to build up to a command that will put all the pieces of the smaller commands together and
- Create a new multidev based on the latest live tag
- Apply upstream updates
- Hotfix deploy those upstream updates to the live environment

After that, we can look at having the all-in-one command take a list of sites as an input, similar to [Terminus mass update](https://github.com/pantheon-systems/terminus-mass-update), for bulk deploying security fixes.

**Comment by ataylorme** [comment]
This plugin is a work in progress but I wanted to get what I have so far up and shared.

I added a [purpose section to the README](https://github.com/terminus-plugin-project/terminus-hotfix-plugin#purpose) so hopefully, that helps as well.

**Comment by uberhacker** [comment]
OK, that makes sense now.  Good idea!  I imagine you will also want the hotfix merged into the dev master branch as well as other working multidev branches eventually in order to prevent potential merge conflicts.  Should always consider these things when deviating from the normal workflow.

**Comment by uberhacker** [comment]
@sean-e-dietrich: You can use `git stash` for that purpose.  Nice meeting you finally at Texascamp.

**Comment by ataylorme** [comment]
> You can use `git stash` for that purpose

@uberhacker I've used that for uncommitted changes locally but I don't think that will work for uncommitted SFTP changes on Pantheon but I could be wrong

**Comment by uberhacker** [comment]
@ataylorme: The [terminus-backup-all-plugin](https://github.com/terminus-plugin-project/terminus-backup-all-plugin) has code that commits changes in sftp mode so that is something you could possibly leverage.

**Comment by ataylorme** [comment]
Yeah, I definitely will ~steal~ borrow from that.

**Comment by uberhacker** [comment]
Plagiarism is certainly allowed.  That's why we call it open source. :)

**Comment by sean-e-dietrich** [comment]
@uberhacker @ataylorme I'm thinking about items that haven't been committed in SFTP mode.

**Comment by uberhacker** [comment]
@sean-e-dietrich: You could switch into git mode and run `git diff > sftp-mode.patch`, `git checkout .`, apply the hotfix, commit, then switch back into sftp mode and run `patch -p1 < sftp-mode.patch`.  For some reason `git apply sftp-mode.patch` doesn't work.

**Comment by sean-e-dietrich** [comment]
@uberhacker That would mean you would have to commit the non committed code in sftp mode first before you could get a patch .... i'm asking if you could do a diff on the code that hasn't been committed to create a patch before hand. Sounds like there would be more of a hassle then anything to get that.

**Comment by uberhacker** [comment]
The `git checkout .` prevents you from committing the changes in git mode.

**Comment by sean-e-dietrich** [comment]
@uberhacker where are you running `git checkout .` at?

**Comment by uberhacker** [comment]
Mounted locally via the [terminus-site-mount-plugin](https://github.com/terminus-plugin-project/terminus-site-mount-plugin)?
